### ISSUE TITLE
[Bug] Stream list not loading

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#14]
Caught that sneaky error:

> popup.js:1 Uncaught TypeError: Cannot read property 'substring' of null
> popup.html:1 Alarm delay is less than minimum of 1 minutes. Alarm "ajax" will fire in approximately 1 minutes.

First line is an error, second line is a warning.
Might be my fault, but I'll look into that later.

**Comment by Kunamatata** [comment]
Hey @Dunedune ! 
I just fixed both an hour ago on the dev branch ;) 
I added an inline check on that substring error and the alarm delay warning isn't justified since the delay is set to 1 minute!

Let me know if you still have a problem, I will be pushing the current state of the extension live tonight.

**Comment by Dune-jr** [comment]
Couldn't find the matching commit
